---
# Don't build an IPA deployment image, instead download upstream images.
create_ipa_image: false
download_ipa: true

# Use a locally hosted CentOS8 cloud image.
use_cirros: true
cirros_deploy_image_upstream_url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
